In [31]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [8]:
prop_data = pd.read_csv("HousePricePrediction.csv")
prop_data = prop_data.fillna(prop_data.mean(numeric_only=True))
prop_data

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.00000
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.00000
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.00000
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.00000
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,180921.19589
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,180921.19589
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,180921.19589
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,180921.19589
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,180921.19589

In [9]:
# one hot encoding

categorical_cols = ['MSZoning', 'LotConfig', 'BldgType', 'Exterior1st']
prop_data = pd.get_dummies(prop_data, columns=categorical_cols)
prop_data

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_C (all),...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,0,60,8450,5,2003,2003,0.0,856.0,208500.00000,False,...,False,False,False,False,False,False,False,True,False,False
1,1,20,9600,8,1976,1976,0.0,1262.0,181500.00000,False,...,False,False,False,True,False,False,False,False,False,False
2,2,60,11250,5,2001,2002,0.0,920.0,223500.00000,False,...,False,False,False,False,False,False,False,True,False,False
3,3,70,9550,5,1915,1970,0.0,756.0,140000.00000,False,...,False,False,False,False,False,False,False,False,True,False
4,4,60,14260,5,2000,2000,0.0,1145.0,250000.00000,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,1936,7,1970,1970,0.0,546.0,180921.19589,False,...,True,False,False,False,False,False,False,False,False,False
2915,2915,160,1894,5,1970,1970,0.0,546.0,180921.19589,False,...,True,False,False,False,False,False,False,False,False,False
2916,2916,20,20000,7,1960,1996,0.0,1224.0,180921.19589,False,...,False,False,False,False,False,False,False,True,False,False
2917,2917,85,10441,5,1992,1992,0.0,912.0,180921.19589,False,...,False,True,False,False,False,False,False,False,False,False
2918,2918,60,9627,5,1993,1994,0.0,996.0,180921.19589,False,...,False,True,False,False,False,False,False,False,False,False

In [12]:
# Column Filteratiom
X = prop_data.drop(columns = ["Id","SalePrice"])
y = prop_data["SalePrice"]

In [27]:
# training
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=12)
X_train = X_train.fillna(X_train.mean(numeric_only=True))
y_train = y_train.fillna(y_train.mean(numeric_only=True))
model = LinearRegression()
model

LinearRegression()

In [28]:
model.fit(X_train,y_train)
model

LinearRegression()

In [29]:
y_pred = model.predict(X_test)
y_pred

array([214569.54454617, 185927.86084607, 156230.22294192, 159183.58559599,
       106021.97186207, 191624.83858457, 223917.98632677, 135530.77209752,
       210729.21495484, 219676.55979064, 203977.69944114, 172628.21139809,
       222956.29225013, 197690.25431254, 220407.24718887, 161170.90982072,
       210038.58305207, 139130.17102713, 173750.61566968, 194257.49942076,
       184993.833166  , 173834.31567013, 188301.01369812, 169238.96559798,
       179366.52759305, 198581.00720073, 198426.27581677, 136975.9780923 ,
       200355.21532366, 173654.34041683, 148576.91838002, 180890.15279656,
       236487.48066307, 141457.49694979, 198797.54616953, 217497.69817352,
       166496.61414063, 162599.61034764, 176848.46003599, 150399.87795101,
       145208.40418018, 168779.28261716, 126622.41630455, 151113.94719507,
       260120.16105433, 182902.0950039 , 192658.82150531, 161978.46573304,
       185327.2869848 , 149766.23388452, 163275.91541447, 172760.05053862,
       173888.63833695, 211089.01277006, 151193.56735302, 193971.6328825 ,
       230584.54382576, 198376.03396801, 205422.34072772, 186356.95279389,
       176763.33469829, 247637.30946966, 154602.50416719, 174386.28770979,
       161471.54833524, 197689.68848265, 152328.59317273, 156614.41654332,
       180052.71540303, 145634.66711227, 179025.94417988, 153828.21927318,
       139371.02016515, 155005.73186677, 216000.00974853, 220164.79567773,
       150998.76506438, 244617.57185315, 108587.79149642, 174285.7993773 ,
       142038.6862214 , 158875.31996809, 188671.47880405, 156434.09503342,
       204180.41484488, 171351.73188127, 173776.59687001, 165600.94060955,
       196149.86925361, 193646.33990269, 152096.55247981,  83937.39772049,
       157609.53535718, 237994.09191708, 169751.1993279 , 203371.29326913,
       196555.24136078, 217326.9100999 , 172355.6153593 , 186687.34007106,
       230568.87944686, 156691.47407347, 162360.81487743, 153420.2007468 ,
       164428.03494246, 163499.91513396, 142827.7536169 , 204869.0987323 ,
       197955.61353751, 157762.72667321, 190031.66593027, 184657.87993085,
       210151.84763527, 218932.2520013 , 201374.77148785, 195641.32206393,
       199744.07395038, 163707.11316255, 233121.067018  , 191735.44008738,
       149899.53857272, 161322.93386821, 165855.33970248, 215373.65271805,
       186207.81449798, 114823.62469277, 201325.58553741, 162104.74999115,
       195946.6980407 , 199405.52013056, 170951.36397426, 163543.98099326,
       162558.30696582, 166417.58282874, 205193.72433044, 126411.20319786,
       155473.39198798, 153291.01227666, 182540.46469532, 230298.14783562,
       159929.99675206, 167415.02158177, 204542.96051656, 226927.82752877,
       148351.94802018, 198325.48908104, 199543.28412887, 169707.57349219,
       178619.59890865, 190468.96408573, 135890.00922055, 200299.69180552,
       222412.86593384, 169440.1089693 , 191083.79366478, 161444.2160276 ,
       163676.94389313, 221076.24573137, 145226.22321479, 165702.12690106,
       223410.69972273, 154426.37012929, 165622.75994636, 199006.99938041,
       110513.0362391 , 217611.47684407, 159336.45803232, 137745.85915595,
       113536.23512271, 218560.77193761, 216380.84931463, 219182.53058025,
       213443.08522543, 178745.57765549, 187699.0146861 , 189442.30224062,
       173878.95950215, 157544.09356682, 135084.16752082, 206671.08225052,
       164633.12553844, 155186.2588643 , 189158.77999776, 206027.50054335,
       231792.88846114, 227839.92811332, 215584.52826091, 164670.85910909,
       164846.88478702, 190758.96004403, 156403.68421727, 163952.79073983,
       211418.62808727, 163061.86416575, 205952.97594209, 249407.98473931,
       211058.02388016, 180885.257901  , 223127.02402173, 192265.07284876,
       190021.07995671, 130628.07662704, 204680.00821832, 149138.38979114,
       131488.77736398, 155562.31168689, 149886.50461011, 203171.19663892,
       185827.29359508, 193243.1992282 , 186391.20678629, 237044.90754995,
       157928.50655578, 201373.14714214, 191468.42986111, 179156.00053774,
       220626.15642965, 239559.12236418, 198310.12278363, 229231.93968209,
       163649.88568048, 211864.56776612, 188871.76566551, 144644.36535351,
       167423.58255478, 192881.85347705, 142507.4509214 , 185116.58420828,
       155765.09770077, 188307.75609449, 177976.16538361, 174776.03661397,
       173620.32833526, 199634.25056432, 188687.22683051, 174164.74549037,
       140043.9637933 , 158008.14158745, 197269.07169159, 160926.30379733,
       195676.70299181, 202552.32714299, 176338.82778667, 151315.61210405,
       144291.71339505, 243031.70119806, 197536.45163696, 210330.24578259,
       178740.89983758, 214822.38655851, 161021.25952212, 134659.26139506,
       173331.18250864, 206875.90228777, 211225.61582187, 167988.25444845,
       172340.86289774, 153553.50435012, 152002.40570267, 158100.42467403,
       158549.18802137, 188154.47242901, 206962.10623704, 154439.13694887,
       185683.83023226, 180123.04897992, 170305.01303779, 230273.65384723,
       224115.70513509, 210261.77323444, 201979.07767116, 150844.09447278,
       220523.16783044, 195659.54821751, 167333.66346014, 233290.58542164,
       172470.60770832, 214907.59315615, 101084.28543556, 192905.083656  ,
       147499.81699739, 221971.05182948, 197426.76989937, 225672.35520749,
       192045.92253829, 190177.13296206, 217289.39580333, 156824.35950631,
       154805.06292411, 224349.62747394, 202839.85272259, 136354.68200966,
       161786.28992768, 151178.97427988, 199938.09776241, 191903.28447664,
       207408.81858034, 162453.98706745, 117797.24665835, 184479.97685235,
       158324.60086143, 140191.22554772, 209567.80460035, 200126.5010529 ,
       190653.96749199, 213778.1973954 , 179168.01139853, 201104.14482818,
       195096.28657226, 148139.00364723, 205296.33600787, 193334.69265519,
       171446.85964488, 140853.99730033, 179672.41222694, 166741.04365949,
       166677.52421838, 176632.58812315, 174632.63646755, 162405.38501316,
       161493.16571543, 224942.18510244, 166386.57433185, 161666.26894954,
       128063.31331618, 138466.448592  , 195888.8620803 , 225570.79379838,
       180460.62756195, 184239.82408279, 161386.90918289, 202905.5087347 ,
       140172.51901603, 223851.78593953, 202595.36046429, 152815.02360651,
       180998.31031949, 182170.64594123, 146110.76601196, 179720.56391898,
       219592.61764546, 147289.94782975, 166102.20544941, 201530.91389428,
       191530.37476666, 232889.14839934, 193571.38893093, 164316.53112304,
       195197.57616092, 225438.1533265 , 165984.98398945, 173641.49181641,
       255620.98567849, 208613.82848656, 175004.4032674 , 195309.13681071,
       173945.1191672 , 193973.62590362, 387767.94703859, 173259.16634332,
       197066.20510176, 149835.29623439, 151760.61879946, 192614.19898596,
       179464.41473692, 183470.4360888 , 170592.19126773, 203528.59841409,
       126534.15121183, 154614.52433701, 165963.0832101 , 194512.20381505,
       218546.41383556, 184228.27784022, 171145.24427666, 174853.88162962,
       188414.17530659, 230162.87788928, 127698.1163549 , 209088.30600978,
       194313.41425132, 171154.7220853 , 174572.19931297, 232492.11173675,
       158481.70539915, 194160.75788053, 152818.56298719, 201322.78667449,
       189721.40647063, 252655.40322671, 176256.63788666, 197775.50431018,
       211234.97187491, 227570.46365695, 137919.34842146, 162988.29634716,
       157849.20462627, 159218.99419311, 225117.18380767, 153144.88625585,
       186877.45658811, 183272.20654582, 199341.25291607, 165660.43555719,
       167382.35051498, 164287.22382562, 145549.6648949 , 178193.0059688 ,
       172395.10695614, 161308.6951451 , 183262.18622826, 203735.65302641,
       213132.07369104, 167227.84197262, 156047.64505433, 115566.61819127,
       206800.78461798, 199500.56117222, 178435.36446095, 185647.67739007,
       205227.3422318 , 147943.79556236, 196389.75285233, 190048.26210607,
       175184.54608051, 117896.79419471, 154426.37012929, 190716.64836189,
       170695.97171186, 172072.19548929, 171945.86035022, 174802.54208222,
       197142.66928883, 164547.91312319, 166965.03403946, 150889.2983121 ,
       219802.44915082, 183436.13456223, 139021.67388768, 254008.01886516,
       243013.75969503, 167553.66354344, 172106.99324395, 172981.49270792,
       190048.23075818, 197417.77048622, 216818.28647342, 225933.68074179,
       192483.83050075, 203965.22224253, 153263.13708951, 229671.50187829,
       190228.44366523, 189859.05368517, 201797.24033563, 142713.47109539,
       189087.2503746 , 208394.6554322 , 172335.6785257 , 166677.52421838,
       231431.68928   , 128454.22590939, 202291.67440843, 173028.55921275,
       196648.9459601 , 162616.28828508, 164386.86485532, 184890.00833818,
       131780.13470334, 196699.77336664, 174455.90783056, 141316.69083472,
       200184.12697315, 181317.339126  , 165388.59778499, 169887.10829071,
       196619.49448435, 170214.67443405, 193372.80282761, 163536.50861154,
       197762.62146176, 201108.68521209, 210470.99230386, 175012.77091405,
       186876.843178  , 199749.28788954, 133311.988149  , 176598.97233986,
       157761.22478204, 207167.42620026, 171830.25624895, 154197.09065246,
       200090.21534198, 152510.72887212, 214090.12631535, 177560.06787945,
       220727.60540082, 147055.53943318, 163169.38144319, 161478.20171865,
       195613.10926823, 166281.80721691, 209400.49466589, 214976.55292728,
       159778.06138445, 206624.3497339 , 156134.77628661, 179191.36189504,
       190456.52780691, 206944.86185541, 155855.43871162, 187849.97093733,
       175659.96572629, 168660.92209566, 191812.59863299, 169922.43163073,
       195033.67182093, 196086.97710834, 175498.13176195, 147445.51270335,
       210347.10424654, 220334.1293338 , 208598.91726908, 168460.32527475,
       226016.25915247, 234976.77665421, 212279.90967475, 190107.69055408,
       187184.74126765, 157674.76639157, 162413.90517974, 189953.75128017,
       187776.20660149, 188064.40097746, 196488.67230366, 154954.55071862,
       199439.74654291, 156377.446014  , 162759.71227345, 198568.17777537,
       129834.81463372, 161468.79224694, 140703.41026269, 238330.41738175,
       172802.67990756, 189071.74360109, 194988.45394438, 205426.2665824 ,
       159366.48970113, 186601.64575197, 217133.32571835, 166768.26172694,
       158195.07350453, 208838.02718424, 148159.64260612, 171393.77228739,
       178085.33446092, 182720.24031749, 130354.714087  , 209187.31585678,
       150350.85085231, 211755.67550714, 148784.37895865, 144660.06751418,
       246235.627425  , 205153.34463108, 144770.20378001, 175876.51717514,
       175767.98204547, 163705.1024561 , 172157.4716832 , 167648.82551792,
       168159.0695385 , 197884.15216381, 207407.09642978, 177666.0054031 ,
       175992.70155136, 133202.86668811, 160377.37076285, 165310.85685705,
       240265.21502848, 204512.02821055, 173623.12154478, 163755.72477297])

In [32]:
r2 = r2_score(y_test, y_pred)
r2

0.31390494638584066